version: '3.8'

services:
  r1:
    image: frrouting/frr:latest
    container_name: r1
    privileged: true
    volumes:
      - ./r1:/etc/frr
    networks:
      fuzz_net:
        ipv4_address: 192.168.56.201


networks:

  fuzz_net:
    driver: macvlan
    driver_opts:
      parent: enp0s8
    ipam:
      config:
        - subnet: 192.168.56.0/24

