frr version 8.4_git
frr defaults traditional
hostname r1
log file /var/log/frr/frr.log
no ipv6 forwarding
!
interface eth0
 ip address 192.168.56.201/24
 ip ospf network point-to-point
!
interface eth1
 ip address 10.10.10.11/24
 ip ospf network point-to-point
!
router ospf
 ospf router-id 2.2.2.2
 network 10.10.10.0/24 area 0
 network 192.168.56.0/24 area 0
!

